appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32ce7d3aeb3c070044c5fb
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: Wt3KXWEP9+FdGQ6bs7prY1aber1M2momKwJHLWW9f6ZZKT3uIKaZaYT8oCz7cB+MQ+QoMam1H0DQFc7Y4SneklPg1daj4UWINflkqL7zhsXhG746CB/oPqb5hUnRdlmsPjFGmCamk/oZy/ULxrKoRLwuFrgruLkH4h0IdQKpaRBgf4HtiHqdLC3wbA849Fz9zqgJCgTmpXEnHaCsS/TDROoQqSzz8BhmRYBygMBkEGAoL/v3AcVYxegi1+Ba/GTihmTYurSsakFakWgU6P5ZMKrpIlmZnlAIqpTV69A+CMpaUMcKN/P2KI1D6jfTIBCnTS5kxtZIlUgsrox8/sapRSrfbN0PRUpqVfBQby0d47irkPK1/LrbfEs/8H5rOcf9jJy/LUBZO16Zws1ey6S8gi6P0rPt9a5/5352TxOSAQLOAjYsQIzdtKCwQ/tEtABMrqRpSp8FBV3+I1g0z7DOr6jxu8qgmVuwYg9dFltCXzCQxq8DpjzLiC7e7cE5O48a3S8oTu31pkkJSx8YpJ8NjwgDwrQu10XC9ZuMf53PIT4tG5ezSGYCN+Fa4cedVxhmJwWygJZKpUIlvYqpXV4ZafKyZ0aVjxgqE6I+ixotaNCFZaq7mQNiUmNG/L/sKJblv5w685UBFiqAOVvx+Es9uvruH9kWP5CON1lC+RuRAe0=}
